version: "3.4"
services:
  app:
    container_name: flaskblog
    restart: always
    build:
      context: ..
      target: postgres_test
    ports:
      - 5000:5000
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://dev_user:dev_password@postgres:5432/test_flaskblog"
    links:
      - postgres
    tty: true
  postgres:
    container_name: postgres
    image: postgres:12.3
    restart: unless-stopped
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=test_flaskblog
